### PR TITLE
How to Implement Slack-like Login on iOS with Auth0

### PR DESCRIPTION
**Pull request by sebadoom**
How to Implement Slack-like Login on iOS with Auth0 draft. Full post. Bug in example. Some images are videos (the ones with the OS X dock visible). RFC.
how to implement slack-like login on ios with auth0

### CODE REVIEW

**Comment by sebadoom** [comment]
Use applinks instead of webcredentials and add an additional warning for the use of Gmail.
how to implement slack-like login on ios with auth0 1

**Comment by woloski** [comment]
would be great a video of the whole ux

**Comment by hzalaz** [comment]
@sebadoom @woloski we should not provide any "ready to use" sample since it wouldn't work since they will need access to our apple dev account. This is because we specified that apps with our Apple Dev TeamID should open those links and apple validates that with the certs you use to sign the app before running it.
My suggestion will be to use the passwordless sample and tell them to set the flag in Lock and add the entitlements in Xcode, the rest is just account configuration.

**Comment by hzalaz** [comment]
@sebadoom you can use 
```swift
A0Lock.sharedLock()
```
to get a shared lock instance that loads Auth0 credentials from `Info.plist` file.

Also this will only work in iOS 9, Lock checks that and falls back to code input if running in iOS 8 or lower

**Comment by sebadoom** [comment]
@hzalaz I agree. I will delete the sample repo and tell people in the post to use the generic samples as base. I will also add a note clarifying magic link only works on iOS 9 and Lock automagically fallsback to code input on previous versions.

@woloski let me see if I can take a full video capture of the login process. I will need to set up a different email than the one I normally use since the Gmail app opens links internally. Where would you like me to put it in the post? At the end?

**Comment by sebadoom** [comment]
Latest draft, switched repos to the mobile samples one, added full flow video. Missing: icon
how to implement slack-like login on ios with auth0 2

**Comment by hzalaz** [comment]
@sebadoom I'd rather use the link to download the seed sample (configured with their account credentials if they are logged in) instead of making them clone the repo with all the samples and navigate a directory.

**Comment by sebadoom** [comment]
@hzalaz Oh, where's that? Let me see if I can find it.

**Comment by hzalaz** [comment]
@sebadoom it's not documented but we use it in our docs site, not sure if it'll work in the blog though. Check the get seed project button [here](https://auth0.com/docs/connections/passwordless/ios-email-swift)

**Comment by sebadoom** [comment]
@hzalaz I don't think that will work. The client id is set in the URL: https://auth0.com/docs/Mobile-Samples.iOS/master/create-package?path=Passwordless-Email/Lock/Swift&filePath=Passwordless-Email/Lock/Swift/Passwordless-Email/Info.plist&type=replace&clientId=FyFnhDX2kSqtpMZ6pGe6QpQuJmD7s4dj

**Comment by hzalaz** [comment]
@sebadoom without that parameter it should work too, otherwise just add a link to the directory in the repo of samples.

**Comment by sebadoom** [comment]
@hzalaz Just tested the link without the client id. It creates a ZIP file without changing the Auth0 ID, so it's just like cloning it from GitHub.

**Comment by hzalaz** [comment]
@sebadoom some last comments, we should use the domain `samples.auth0.com`, the app screenshot should have the device frame and finally we should use 

```swift 
A0Lock.sharedLock()
```

instead of the singleton app, I need to change the samples to use that but it's the same behaviour but does not require the user to keep a singleton.

Also for the request, I'd rather put the curl command, and maybe output rather than the screenshot to our site that does not give any help (we can add the link).

**Comment by sebadoom** [comment]
We should use samples.auth0.com for what? As an Auth0 test account?

I didn't use A0Lock.sharedLock because of the way the samples create the instance of the A0Lock object (they don't use sharedLock, and by taking a look at the Lock code I noticed sharedLock uses a different instance from the ones returned by other constructors). So until the samples are updated we cannot tell people to do that based on our example.

I did not use the Curl command because then we need to explain how to get the JWT, and that means people need to browse to that page anyway.

**Comment by hzalaz** [comment]
`samples.auth0.com` is to avoid adding your domain `speyrott.auth0.com`.
About `A0Lock.sharedLock()`, the samples are coded that way since I don't have time to keep everything up to date and build stuff so they are a little outdated.

Good point about the JWT, it's harder to explain how to get one.

**Comment by hzalaz** [comment]
A little more for `A0Lock.sharedLock()` is that we should use it since I want this code snippet to be easily use by copy-pasting without adding a lot of dependencies like creating that `Application` class, I'd make these snippets agnostic of the sample. e.g.: I'd replace 

```swift
controller.onAuthenticationBlock = { (profile, token) in
    let app = Application.sharedInstance
    app.token = token
    app.profile = profile
    self.dismissViewControllerAnimated(true, completion: { self.performSegueWithIdentifier("UserLoggedIn", sender: self) })
}
```

and use 

```swift
controller.onAuthenticationBlock = { (profile, token) in
   // You're authenticated
    self.dismissViewControllerAnimated(true, completion:nil)
}
```

**Comment by sebadoom** [comment]
@hzalaz I undestand. Would you like me to send a PR for the iOS samples with the sharedLock change? My point is we need to have this available when the post goes live (ASAP) as people are bound to follow the steps and try it.

**Comment by sebadoom** [comment]
@hzalaz it would also include updates pods.

**Pull request merged**
