### PR TITLE
Getting Started with Lock ep 3: Redirect vs Popup mode

### PR DESCRIPTION
**Pull request by nodebotanist**

### CODE REVIEW

**Comment by mgonto** [comment]
@nodebotanist can you update to tomorrow's date and add a description and we can merge.

This blog post was forgotten here. If you see your PR isn't merged ping Ryan or Tony

**Comment by nodebotanist** [comment]
This should be ready to go @chenkie

**Comment by mgonto** [comment]
@nodebotanist you missed the file name: http://d.pr/i/15D0E

**Comment by mgonto** [comment]
it also needs to change with the date

**Pull request merged**
