### PR TITLE
Post: "I built a Twitter bot using Webtask and Data.gov"

### PR DESCRIPTION
**Pull request by thzinc**
I've been talking with Glenn Block about this post for a few weeks.

### CODE REVIEW

**Comment by glennblock** [comment]
Thanks for sending this @thzinc 👍

**Comment by glennblock** [comment]
+ @diegopoza

**Comment by unicodeveloper** [comment]
@glennblock I'll review it!

**Comment by glennblock** [comment]
It has been reviewed already and I sent him edits.

**Comment by glennblock** [comment]
We are ready to merge and publish.

**Comment by glennblock** [comment]
Tony is set to publish tomorrow in the AM

**Comment by unicodeveloper** [comment]
@glennblock awesome!

**Comment by thzinc** [comment]
I merged the Auth0 style guide edits. Is there anything else holding this up?

**Comment by glennblock** [comment]
Hi Daniel

Thanks. This is on schedule to post, should be today.

Glenn

**Comment by thzinc** [comment]
@glennblock @RamiroND, it looks like some of the Markdown formatting used in my post isn't directly compatible with the Auth0 blog's Markdown processor. I used the three-tick + source type notation, but that seems like it's not supported.

**Comment by glennblock** [comment]
Hi Daniel. I fixed it. For some reason I had to add a blank line before the
ticks.

**Pull request merged**
